// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKT2RfAwsTV2uz2_fvNCXd16IVPzW7Oac',
    appId: '1:742189811367:web:aecd5f6cd8f225d0aa3d82',
    messagingSenderId: '742189811367',
    projectId: 'elvalecliente',
    authDomain: 'elvalecliente.firebaseapp.com',
    databaseURL: 'https://elvalecliente-default-rtdb.firebaseio.com',
    storageBucket: 'elvalecliente.appspot.com',
    measurementId: 'G-5LJLY29RE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlx5MOsJH3D21G5BNd_LN0mnJAjY3Ii54',
    appId: '1:742189811367:android:4db76b5692149288aa3d82',
    messagingSenderId: '742189811367',
    projectId: 'elvalecliente',
    databaseURL: 'https://elvalecliente-default-rtdb.firebaseio.com',
    storageBucket: 'elvalecliente.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBPM7-TRd4Ec-cKxw63loWCaPL60W4oaI',
    appId: '1:742189811367:ios:97a343fe20b60ec8aa3d82',
    messagingSenderId: '742189811367',
    projectId: 'elvalecliente',
    databaseURL: 'https://elvalecliente-default-rtdb.firebaseio.com',
    storageBucket: 'elvalecliente.appspot.com',
    iosClientId: '742189811367-5k1g2edpoed67iaojsuqc6m2c9ud3cd8.apps.googleusercontent.com',
    iosBundleId: 'com.elvale.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBPM7-TRd4Ec-cKxw63loWCaPL60W4oaI',
    appId: '1:742189811367:ios:97a343fe20b60ec8aa3d82',
    messagingSenderId: '742189811367',
    projectId: 'elvalecliente',
    databaseURL: 'https://elvalecliente-default-rtdb.firebaseio.com',
    storageBucket: 'elvalecliente.appspot.com',
    iosClientId: '742189811367-5k1g2edpoed67iaojsuqc6m2c9ud3cd8.apps.googleusercontent.com',
    iosBundleId: 'com.elvale.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI9xZKuX7U6WWUspliXejVlq-IMGb2WEI',
    appId: '1:742189811367:web:7b3eb84e2348b67caa3d82',
    messagingSenderId: '742189811367',
    projectId: 'elvalecliente',
    authDomain: 'elvalecliente.firebaseapp.com',
    databaseURL: 'https://elvalecliente-default-rtdb.firebaseio.com',
    storageBucket: 'elvalecliente.appspot.com',
    measurementId: 'G-RY98GGXYQV',
  );
}
